### ISSUE TITLE
On Stream Review

### ISSUE THREAD

**Issue by braddotcoffee** [ItsThompson/currency-converter#1]
## (Minor) Setup gofmt pre-commit
* You could [maybe use this](https://github.com/edsrzf/gofmt-git-hook/blob/master/fmt-fix) or a similar approach to make sure that you don't accidentally commit unformatted code
* Go is super opinionated about this, so I think it's best to try to set something like this up

## Caching
* [Functionality] It would be nice to be able to forcibly update the cache
* Separation of concerns:
    * Right now, your caller has to care about the cache, but the API *also* has to care about the cache
    * I think there are two viable models here: 
        1. encapsulate the cache inside of the API
        2. The API is cache agnostic
 
![image](https://github.com/ItsThompson/currency-converter/assets/17772186/7c276315-00eb-4bc2-b85f-699445df6b07)

    * I would prefer to see you move to either of these two models but the "encapsulate the cache" option is probably better
    * In this case, your main should never have to call any of the cache functions

**Comment by ItsThompson** [comment]
Completed with Pull Request https://github.com/ItsThompson/currency-converter/pull/2
